name: forge
description: "A unified platform for data and ML pipelines."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

    # Data Ingestion
  csv: ^5.0.0
  image_picker: ^0.8.4+1

  # Data Processing
  image: ^3.1.3 # For image manipulation
  flutter_sound: ^9.0.0 # For audio processing
  ffigen: ^4.1.2 # For calling native code for high-performance tasks like FFT

  # UI & Visualization
  fl_chart: ^0.40.0 # For charts and evaluation dashboard
  flutter_svg: ^1.0.0 # For SVG icons and diagrams
  
  provider: ^6.0.0
  sqflite: ^2.0.0+1
<<<<<<< Updated upstream
  path_provider: ^2.0.2
  hive: ^2.0.4 # A great alternative to shared_preferences for local data storage
  highlight: ^0.7.0

  # State Management
  get: ^4.6.6
  flutter_code_editor: ^0.3.4
  file_picker: ^4.6.1
=======
  sqflite_common_ffi: ^2.3.6
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansDisplay-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSansDisplay-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansDisplay-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSansDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSansDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansDisplay-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/NotoSansDisplay-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/NotoSansDisplay-Italic-VariableFont_wdth,wght.ttf
          style: italic
