name: forge
description: "A unified platform for data and ML pipelines."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+1
<<<<<<< HEAD
  path_provider: ^2.0.2
  hive: ^2.0.4 # A great alternative to shared_preferences for local data storage
  highlight: ^0.7.0
  path: ^1.9.0  # file path utilities
  crypto: ^3.0.3 #for password hashing
  bcrypt: ^1.1.3

  # State Management
  get: ^4.6.6
  flutter_code_editor: ^0.3.4
=======
  sqflite_common_ffi: ^2.3.6
>>>>>>> 8f388566fb19eaeca80e046763d0108eea76739d

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # The line below was uncommented to make sure Flutter knows about your assets directory.
  assets:
    - assets/fonts/
  
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansDisplay-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSansDisplay-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansDisplay-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSansDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSansDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSansDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansDisplay-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/NotoSansDisplay-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/NotoSansDisplay-Italic-VariableFont_wdth,wght.ttf
          style: italic
